CREATE TABLE tools (
too11 INT UNSIGNED, 
tool2 INT UNSIGNED, 
tool3 INT UNSIGNED,
tool4 INT UNSIGNED,
tool5 INT UNSIGNED,
tool6 INT UNSIGNED,
tool7 INT UNSIGNED,
tool8 INT UNSIGNED,
tool9 INT UNSIGNED,
tool10 INT UNSIGNED,
id INT UNSIGNED NOT NULL AUTO_INCREMENT KEY) 
ENGINE MyISAM;
